---
kind: pipeline
type: docker
name: verify-pr
steps:
- name: install
  image: danlynn/ember-cli:3.28.5 # Replace this with madnificent/ember once it includes a browser
  commands:
  - npm ci
- name: lint
  image: danlynn/ember-cli:3.28.5 # Replace this with madnificent/ember once it includes a browser
  commands:
  - npm run lint
- name: dependency-lint
  image: danlynn/ember-cli:3.28.5 # Replace this with madnificent/ember once it includes a browser
  failure: ignore
  commands:
  - npx ember dependency-lint
- name: test
  image: danlynn/ember-cli:3.28.5 # Replace this with madnificent/ember once it includes a browser
  failure: ignore
  commands:
  - npm run test:ember
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-contact-hub
    dry_run: true
    purge: true
trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-contact-hub
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
    build_args:
      - SHOW_APP_VERSION_HASH=true
trigger:
  branch:
    - development
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/frontend-contact-hub
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/frontend-contact-hub
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: fAf5FwcaTb260T5gggfW0MN8sJEIhGzcX0c6SrA5CrMqY1rgaqV2dw==
---
kind: secret
name: docker_password
data: On9Zz9kKgFYinSaBOPNeQSUr9Tq3aoS/ZSV7FvDmP/3QgFQ6C2vlZ7vamAugDfeI+zG9FUyn58hXrFFG4XrS4w==
---
kind: signature
hmac: 45ec8892515b156b06d57e48b92a6082c06c2b9f4ed404a6feb5f706bde4f8d4

...